### ISSUE TITLE
Problem with more than 1 image

### ISSUE THREAD

**Issue by cliffgr** [bopbi/Android-Parallax-ListView-Item#1]
if(position==0) {
               imageView.setImageResource(R.drawable.a1);
           }else if(position==1){
               imageView.setImageResource(R.drawable.a2);
           }else if(position==2){
               imageView.setImageResource(R.drawable.a3);
           }else if(position==3){
               imageView.setImageResource(R.drawable.a4);
           }else if(position==4){
               imageView.setImageResource(R.drawable.a5);
           }else if(position==5){
               imageView.setImageResource(R.drawable.a6);
           }else if(position==6){
               imageView.setImageResource(R.drawable.a7);
           }else if(position==7){
               imageView.setImageResource(R.drawable.a8);
           }else if(position==8){
               imageView.setImageResource(R.drawable.a9);
           }else if(position==9){
               imageView.setImageResource(R.drawable.a10);
           }else if(position==10){
               imageView.setImageResource(R.drawable.a11);
           }

i see dublicate images in the listview..

**Comment by bopbi** [comment]
hehehehe sorry for the late response, i think you could implement your own cell draw, sorry
