### ISSUE TITLE
Parallax Effect Bug.

### ISSUE THREAD

**Issue by DonLiangGit** [bopbi/Android-Parallax-ListView-Item#4]
Bopbi,

in your source code you set matrix.postTranslate in both adapter and activity,
in my practice it will results unexpected background positions.

**Comment by DonLiangGit** [comment]
this only happens on using toolbar instead of actionbar.

**Comment by bopbi** [comment]
hmm i create this before L / Lollipop exist, so should i update it with latest libraries, by using recyclerview and toolbar

or should i create another project? what do you suggest

**Comment by DonLiangGit** [comment]
Clarify the bug again:
Let say I set list item height in xml 230dp, when i continue scrolling the listview without finger up, then down, the item imageviews cannot translate back to the original position, therefore, it looks like a gap between two list item.

I think it is due to visible position in listview,
<code>int first = ListView.getFirstVisiblePosition();
int last = ListView.getLastVisiblePosition(); </code>
or using the <code>invalidate()</code> method for imageview

this is another maybe solution to calculate the translation for imageview.
[link](https://github.com/Ruenzuo/Parallax-ListView-Android/blob/master/app/src/main/java/com/ruenzuo/testingapp/activities/MainActivity.java)

**Comment by bopbi** [comment]
hmm based on your suggested link, previously i have try that way and it has performance issue, that is why i create custom listener and also set the translation on the adapter.

anyway thanks for the suggestion, i am never tested it when the listview item is quite high 

Currently i am try to refactor this lib, hopefully i come with a better solution

**Comment by DonLiangGit** [comment]
bopbi, dont close this issue until it got solved.
And I will work on my side to see the Soundcloud sc.

**Comment by bopbi** [comment]
anyway the reason i set the image matrix on the adapter is to make the the moved image is set to center so the border effect could be minimalized

**Comment by bopbi** [comment]
after searching around it seems to handle the scroll value by using the recyclerview scroll listener

https://developer.android.com/reference/android/support/v7/widget/RecyclerView.OnScrollListener.html#onScrolled(android.support.v7.widget.RecyclerView, int, int)

public void onScrolled (RecyclerView recyclerView, int dx, int dy)

Callback method to be invoked when the RecyclerView has been scrolled. This will be called after the scroll has completed.

Parameters
recyclerView	The RecyclerView which scrolled.
dx	The amount of horizontal scroll.
dy	The amount of vertical scroll.
